import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

import 'package:thanaweya_online/features/teacher/ui/onboarding/widgets/widgets.dart';

/// Builds the animated step view for the teacher form based on the current step.
Widget buildTeacherFormStep({
  required int step,
  required GlobalKey<FormState> s0Key,
  required GlobalKey<FormState> s1Key,
  required GlobalKey<FormState> s2Key,
  required TextEditingController nameCtrl,
  required TextEditingController phoneCtrl,
  required TextEditingController emailCtrl,
  required TextEditingController passCtrl,
  required TextEditingController bioCtrl,
  required int sysIdx,
  required Set<String> subIds,
  required Set<String> trackIds,
  required List<Map<String, dynamic>> subjects,
  required Set<String> stageVals,
  required String mode,
  required String? gov,
  required bool terms,
  required XFile? avatar,
  required XFile? idFront,
  required XFile? idBack,
  required XFile? proof,
  required XFile? paymentReceipt,
  required int selectedPlanIndex,
  required Future<void> Function({
    required String title,
    required Function(XFile?) onImageSelected,
  })
  pick,
  required void Function(XFile?) onAvatar,
  required void Function(XFile?) onIdFront,
  required void Function(XFile?) onIdBack,
  required void Function(XFile?) onProof,
  required void Function(XFile?) onPaymentReceipt,
  required VoidCallback onChangePlan,
  required void Function(int) onPlanChanged,
  required void Function(int) onSysIdx,
  required void Function(String) onSubToggle,
  required void Function(String) onTrackToggle,
  required void Function(String) onStageToggle,
  required void Function(String) onGov,
  required void Function(String) onMode,
  required VoidCallback onTermsToggle,
}) => switch (step) {
  0 => TeacherFormStep0(
    key: const ValueKey(0),
    formKey: s0Key,
    nameController: nameCtrl,
    phoneController: phoneCtrl,
    emailController: emailCtrl,
    passwordController: passCtrl,
    avatarFile: avatar,
    idFrontFile: idFront,
    idBackFile: idBack,
    teacherProofFile: proof,
    onPickImage: pick,
    onAvatarPicked: onAvatar,
    onIdFrontPicked: onIdFront,
    onIdBackPicked: onIdBack,
    onTeacherProofPicked: onProof,
  ),
  1 => TeacherFormStep1(
    key: const ValueKey(1),
    formKey: s1Key,
    teacherSystemIndex: sysIdx,
    onSystemIndexChanged: onSysIdx,
    subjects: subjects,
    selectedSubjectIds: subIds,
    onSubjectToggled: onSubToggle,
    selectedTrackIds: trackIds,
    onTrackToggled: onTrackToggle,
    stages: const [
      {'value': 'first', 'name': 'المرحلة الأولى'},
      {'value': 'second', 'name': 'المرحلة الثانية'},
      {'value': 'third', 'name': 'المرحلة الثالثة'},
    ],
    selectedStages: stageVals,
    onStageToggled: onStageToggle,
    bioController: bioCtrl,
  ),
  2 => TeacherFormStep2(
    key: const ValueKey(2),
    formKey: s2Key,
    selectedGovernorate: gov,
    onGovernorateChanged: (v) => onGov(v ?? ''),
    teachingMode: mode,
    onTeachingModeChanged: onMode,
    governorates: const [
      'البحيرة',
      'القاهرة',
      'الجيزة',
      'الإسكندرية',
      'المنصورة',
      'أسيوط',
      'الشرقية',
      'طنطا',
    ],
    agreedToTerms: terms,
    onAgreedToTermsToggled: onTermsToggle,
  ),
  3 => TeacherFormStep3(
    key: const ValueKey(3),
    selectedPlanIndex: selectedPlanIndex,
    onPlanChanged: onPlanChanged,
  ),
  4 => TeacherFormStep4(
    key: const ValueKey(4),
    selectedPlanIndex: selectedPlanIndex,
    paymentReceiptFile: paymentReceipt,
    onPickImage: pick,
    onPaymentReceiptPicked: onPaymentReceipt,
    onChangePlan: onChangePlan,
  ),
  _ => const SizedBox.shrink(),
};
