import 'dart:math';
import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'package:thanaweya_online/core/network/api_error_handler.dart';
import 'package:thanaweya_online/core/network/api_result.dart';

class TeacherCardsRepo {
  final SupabaseClient _client = Supabase.instance.client;

  /// Fetches all activation codes generated by the teacher.
  Future<ApiResult<List<Map<String, dynamic>>>> getActivationCodes(
    String teacherId,
  ) async {
    try {
      final data = await _client
          .from('activation_codes')
          .select('''
            id, teacher_id, course_id, code, is_used, used_by, used_at, created_at,
            courses(id, title),
            students(id, users(full_name))
          ''')
          .eq('teacher_id', teacherId)
          .order('created_at', ascending: false);

      return ApiResult.success(List<Map<String, dynamic>>.from(data));
    } catch (e) {
      debugPrint('[TeacherCardsRepo] getActivationCodes error: $e');
      return ApiErrorHandler.handleException(e);
    }
  }

  /// Batch generates [count] unique activation codes for the teacher.
  Future<ApiResult<List<Map<String, dynamic>>>> generateActivationCodes({
    required String teacherId,
    String? courseId,
    required int count,
  }) async {
    try {
      final List<Map<String, dynamic>> rowsToInsert = [];
      final random = Random();
      const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

      for (int i = 0; i < count; i++) {
        final part1 = List.generate(4, (_) => chars[random.nextInt(chars.length)]).join();
        final part2 = List.generate(4, (_) => chars[random.nextInt(chars.length)]).join();
        final code = 'TH-$part1-$part2';

        final row = <String, dynamic>{
          'teacher_id': teacherId,
          'code': code,
          'is_used': false,
        };
        if (courseId != null && courseId.isNotEmpty) {
          row['course_id'] = courseId;
        }
        rowsToInsert.add(row);
      }

      final inserted = await _client
          .from('activation_codes')
          .insert(rowsToInsert)
          .select('''
            id, teacher_id, course_id, code, is_used, used_by, used_at, created_at,
            courses(id, title)
          ''');

      return ApiResult.success(List<Map<String, dynamic>>.from(inserted));
    } catch (e) {
      debugPrint('[TeacherCardsRepo] generateActivationCodes error: $e');
      return ApiErrorHandler.handleException(e);
    }
  }

  /// Deletes an unused activation code by ID.
  Future<ApiResult<void>> deleteActivationCode(String codeId) async {
    try {
      await _client
          .from('activation_codes')
          .delete()
          .eq('id', codeId)
          .eq('is_used', false);
      return const ApiResult.success(null);
    } catch (e) {
      debugPrint('[TeacherCardsRepo] deleteActivationCode error: $e');
      return ApiErrorHandler.handleException(e);
    }
  }
}
